%Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

%1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

clc, clf, clear

t1 = 1;
t2 = 2;
t = t1+t2;
sum = 2;

while t <= 4e6
    
    if rem(t,2) == 0
        sum = sum + t;
    end
    
    temp = t1;
    t1 = t2;
    t2 = temp + t1;
    
    t = t1 + t2;
    
end

sum
    
    
    
    
    
    
